# Generated by Django 2.2.6 on 2019-12-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_number', models.CharField(max_length=100, unique=True)),
                ('publication_page_url', models.CharField(max_length=1000)),
                ('priority_date', models.DateField(max_length=100)),
                ('publication_date', models.DateField(max_length=100)),
                ('assignee', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=350)),
                ('description', models.CharField(blank=True, max_length=1500, null=True)),
            ],
        ),
    ]
